name: Deploy

on:
  push:
    branches:
    - main

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
    - name: Get the code
      uses: actions/checkout@v2
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to private registry
      uses: docker/login-action@v1
      with:
        registry: registry.yaakov.online
        username: github-actions
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

    - name: Build and push container
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          registry.yaakov.online/toybox-site:latest
          registry.yaakov.online/toybox-site:${{ github.ref_name }}-${{ github.sha }}-${{ steps.date.outputs.date }}
        platforms: |
          linux/amd64
          linux/arm64