name: Deploy

on:
  push:
    branches:
    - main

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
    - name: Install Podman
      run: |
        sudo apt -y install podman

    - name: Set up QEMU for cross-compilation
      uses: docker/setup-qemu-action@v3

    - name: Get the code
      uses: actions/checkout@v2

    - name: Build Container Image with Podman
      run: |
        podman build --platform linux/arm64,linux/amd64 --manifest toybox .

    - name: Log in to private registry
      uses: redhat-actions/podman-login@v1
      with:
        registry: registry.yaakov.online
        username: github-actions
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Get current date for OCI image
      id: date
      run: |
        echo "date=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

    - name: Push Container Image to Registry
      run: |
        podman push toybox registry.yaakov.online/toybox-site:latest
        pudman push registry.yaakov.online/toybox-site:${{ github.ref_name }}-${{ github.sha }}-${{ steps.date.outputs.date }}
